TOOLS = [
    {
        "name": "financelab.import_preview_csv",
        "scope": "docs:ingest",
        "requires_approval": False,
        "cost_class": "med",
        "max_runtime_ms": 2000,
        "max_memory_mb": 256,
        "network_policy": "none",
        "filesystem_policy": "none",
    },
    {
        "name": "financelab.list_transactions",
        "scope": "finance:read",
        "requires_approval": False,
        "cost_class": "low",
        "max_runtime_ms": 800,
        "max_memory_mb": 128,
        "network_policy": "none",
        "filesystem_policy": "none",
    },
    {
        "name": "financelab.spend_summary",
        "scope": "finance:read",
        "requires_approval": False,
        "cost_class": "low",
        "max_runtime_ms": 1000,
        "max_memory_mb": 128,
        "network_policy": "none",
        "filesystem_policy": "none",
    },
    {
        "name": "financelab.commit_import",
        "scope": "finance:write",
        "requires_approval": True,
        "cost_class": "high",
        "max_runtime_ms": 3000,
        "max_memory_mb": 256,
        "network_policy": "none",
        "filesystem_policy": "none",
    },
    {
        "name": "financelab.write_transaction",
        "scope": "finance:write",
        "requires_approval": True,
        "cost_class": "high",
        "max_runtime_ms": 1500,
        "max_memory_mb": 256,
        "network_policy": "none",
        "filesystem_policy": "none",
    },
]
