TOOLS = [
    {
        "name": "timelab.capture_task",
        "scope": "time:write",
        "requires_approval": False,
        "cost_class": "low",
        "max_runtime_ms": 800,
        "max_memory_mb": 128,
        "network_policy": "none",
        "filesystem_policy": "none",
    },
    {
        "name": "timelab.list_tasks",
        "scope": "time:read",
        "requires_approval": False,
        "cost_class": "low",
        "max_runtime_ms": 600,
        "max_memory_mb": 128,
        "network_policy": "none",
        "filesystem_policy": "none",
    },
    {
        "name": "timelab.update_task",
        "scope": "time:write",
        "requires_approval": False,
        "cost_class": "low",
        "max_runtime_ms": 800,
        "max_memory_mb": 128,
        "network_policy": "none",
        "filesystem_policy": "none",
    },
    {
        "name": "timelab.capture_goal",
        "scope": "time:write",
        "requires_approval": False,
        "cost_class": "low",
        "max_runtime_ms": 800,
        "max_memory_mb": 128,
        "network_policy": "none",
        "filesystem_policy": "none",
    },
    {
        "name": "timelab.list_goals",
        "scope": "time:read",
        "requires_approval": False,
        "cost_class": "low",
        "max_runtime_ms": 600,
        "max_memory_mb": 128,
        "network_policy": "none",
        "filesystem_policy": "none",
    },
    {
        "name": "timelab.weekly_review",
        "scope": "time:read",
        "requires_approval": False,
        "cost_class": "med",
        "max_runtime_ms": 1500,
        "max_memory_mb": 192,
        "network_policy": "none",
        "filesystem_policy": "none",
    },
]
