TOOLS = [
    {
        "name": "idealab.capture_idea",
        "scope": "ideas:write",
        "requires_approval": False,
        "cost_class": "low",
        "max_runtime_ms": 800,
        "max_memory_mb": 128,
        "network_policy": "none",
        "filesystem_policy": "none",
    },
    {
        "name": "idealab.list_ideas",
        "scope": "ideas:read",
        "requires_approval": False,
        "cost_class": "low",
        "max_runtime_ms": 500,
        "max_memory_mb": 64,
        "network_policy": "none",
        "filesystem_policy": "none",
    },
    {
        "name": "idealab.evaluate_idea",
        "scope": "ideas:read",
        "requires_approval": False,
        "cost_class": "med",
        "max_runtime_ms": 1200,
        "max_memory_mb": 128,
        "network_policy": "none",
        "filesystem_policy": "none",
    },
    {
        "name": "idealab.plan_experiment",
        "scope": "ideas:write",
        "requires_approval": False,
        "cost_class": "med",
        "max_runtime_ms": 1200,
        "max_memory_mb": 128,
        "network_policy": "none",
        "filesystem_policy": "none",
    },
    {
        "name": "idealab.log_experiment_result",
        "scope": "ideas:write",
        "requires_approval": False,
        "cost_class": "low",
        "max_runtime_ms": 800,
        "max_memory_mb": 128,
        "network_policy": "none",
        "filesystem_policy": "none",
    },
]
