TOOLS = [
    {
        "name": "researchlab.ingest_note",
        "scope": "research:write",
        "requires_approval": False,
        "cost_class": "low",
        "max_runtime_ms": 1200,
        "max_memory_mb": 128,
        "network_policy": "none",
        "filesystem_policy": "none",
    },
    {
        "name": "researchlab.create_collection",
        "scope": "research:write",
        "requires_approval": False,
        "cost_class": "low",
        "max_runtime_ms": 700,
        "max_memory_mb": 64,
        "network_policy": "none",
        "filesystem_policy": "none",
    },
    {
        "name": "researchlab.list_collections",
        "scope": "research:read",
        "requires_approval": False,
        "cost_class": "low",
        "max_runtime_ms": 700,
        "max_memory_mb": 64,
        "network_policy": "none",
        "filesystem_policy": "none",
    },
    {
        "name": "researchlab.add_to_collection",
        "scope": "research:write",
        "requires_approval": False,
        "cost_class": "low",
        "max_runtime_ms": 800,
        "max_memory_mb": 64,
        "network_policy": "none",
        "filesystem_policy": "none",
    },
    {
        "name": "researchlab.search",
        "scope": "research:read",
        "requires_approval": False,
        "cost_class": "med",
        "max_runtime_ms": 1500,
        "max_memory_mb": 192,
        "network_policy": "none",
        "filesystem_policy": "none",
    },
    {
        "name": "researchlab.context_pack",
        "scope": "research:read",
        "requires_approval": False,
        "cost_class": "med",
        "max_runtime_ms": 1800,
        "max_memory_mb": 192,
        "network_policy": "none",
        "filesystem_policy": "none",
    },
]
