TOOLS = [
    {
        "name": "digesthub.subscribe_daily",
        "scope": "digest:write",
        "requires_approval": False,
        "cost_class": "low",
        "max_runtime_ms": 700,
        "max_memory_mb": 64,
        "network_policy": "none",
        "filesystem_policy": "none",
    },
    {
        "name": "digesthub.subscribe_weekly",
        "scope": "digest:write",
        "requires_approval": False,
        "cost_class": "low",
        "max_runtime_ms": 700,
        "max_memory_mb": 64,
        "network_policy": "none",
        "filesystem_policy": "none",
    },
    {
        "name": "digesthub.unsubscribe",
        "scope": "digest:write",
        "requires_approval": False,
        "cost_class": "low",
        "max_runtime_ms": 600,
        "max_memory_mb": 64,
        "network_policy": "none",
        "filesystem_policy": "none",
    },
    {
        "name": "digesthub.preview_daily",
        "scope": "digest:read",
        "requires_approval": False,
        "cost_class": "med",
        "max_runtime_ms": 1500,
        "max_memory_mb": 192,
        "network_policy": "none",
        "filesystem_policy": "none",
    },
    {
        "name": "digesthub.send_now",
        "scope": "digest:write",
        "requires_approval": False,
        "cost_class": "med",
        "max_runtime_ms": 1800,
        "max_memory_mb": 192,
        "network_policy": "none",
        "filesystem_policy": "none",
    },
]
